class HelpMenu:
    # display help menu
    def display():
        print("\n-----Available commands-----")
        print("1:     /exit                          -- exits shop")
        print("2:     /loadNew                       -- loads a new inventory and account to the bullypy database (overwrites existing")
        print("                                         inventory data and pushes default account to db)")
        print("3:     /viewAll <category>            -- view items in store with argument support.")
        print("\n       USAGE: /viewAll            - shows all items in store")
        print("              /viewAll categories - shows all categories available in store")
        print("              /viewAll hats       - shows all hats in store (this can be changed to any category.")
        print("                                    category can be plural/singular or uppercase/lowercase")
        print("                                    ie. /viewAll Hats, /viewAll Hat, /viewAll hats, /viewAll hat all work\n")
        print("4:     /viewCart                      -- view items in cart")
        print("5:     /addToCart <num> <itemID>      -- add the specified number of items to cart")
        print("6:     /removeFromCart <num> <itemID> -- remove the specified number of items from cart")
        print("7:     /checkout                      -- checkout items in cart")
        print("8:     /viewHistory                   -- view order history")
        print("9:     /editAccount <infoType>        -- edit account infomation. <infoType> can be shipping, payment, name, or login")
        print("10:    /viewAccount                   -- view account details")
        print("11:    /deleteAccount                 -- deletes currently signed in account from database")
        print()
